Grade_Calculator/config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :grades
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  
  
  
  
  get 'calculator/gradeCalculator'
  get 'calculator/gradeTable'
  get 'login/loginPage'
  get 'welcome/index'
  get 'home_page/index'
  get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :login
  
  root 'users#new'
end

Grade_Calculator/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Grade_Calculator/app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :user

end

Grade_Calculator/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :grades
  
  validates :email, presence: true, uniqueness: true
end

Grade_Calculator/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    add_flash_types :danger, :info, :warning, :success, :alert

end

Grade_Calculator/app/controllers/grades_controller.rb
class GradesController < ApplicationController
    def create
        @user = User.find(session[:user_id])
        #grade = @user.grades.create(grade_params)
        @grade= @user.grades.first_or_create(grade_params).update(grade_params)
        flash[:notice] = 'Successfully checked in'
        redirect_to calculator_gradeCalculator_path
        
    end
    private
    
    
    def grade_params
       params.require(:grade).permit(:assignment1,:assignment2,:assignment3,:assignment4,:assignment5,:assignment6,:assignment7,:assignment8,:assignment9,:assignment10, :gradeNum1, :gradeNum2, :gradeNum3, :gradeNum4, :gradeNum5, :gradeNum6, :gradeNum7, :gradeNum8, :gradeNum9, :gradeNum10, :wieght1, :weight2, :weight3, :weight4, :weight5, :weight6, :weight7, :weight8, :weight9, :weight10, :weightAvg, :result) 
    end
end

Grade_Calculator/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end  
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to calculator_gradeCalculator_path
    else
      flash.now.alert = "Invalid email or password"
      render new_session_path
    end
  end  
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
  
end

Grade_Calculator/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    redirect_to new_session_path
  end

  # GET /users/new
  def new
    @user = User.new
    
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :studentName, :schoolName)
    end
end

Grade_Calculator/app/helpers/application_helper.rb
module ApplicationHelper
end

Grade_Calculator/app/helpers/calculator_helper.rb
module CalculatorHelper
end

Grade_Calculator/app/helpers/grades_helper.rb
module GradesHelper
end

Grade_Calculator/app/helpers/home_page_helper.rb
module HomePageHelper
end

Grade_Calculator/app/helpers/sessions_helper.rb
module SessionsHelper
    def login(user)
        session[:user_id] = user.id;
    end
    
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent.signed[:remember_token] = user.remember_token
    end
    
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
    
    def current_user
        if(user_id = session[:user_id])
            @current_user = User.find_by(id: user_id)
        else (user _id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if(user && user.authenticated?(cookies[:remember_token]))
                login user
                @current_user = user
            end
        end
    end
    
    def sign_in?
        !(current_user.nil?)
    end
    
    def logout
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
    
end

Grade_Calculator/app/helpers/users_helper.rb
module UsersHelper
end

Grade_Calculator/app/views/calculator/gradeCalculator.html.erb
<!DOCTYPE html>
<!-- HTML file for Homepage of ITIS 3135 Project -->

<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Class Grade Calculator</title>
    <link rel="stylesheet" type="text/css" href="../stylesheets/main.css">
    <link rel="icon" type="image/x-icon" href="https://my.uncc.edu/sites/all/themes/custom/my_unc_charlotte/favicon.ico"/>
    <script src="../scripts/main.js"></script>
</head>

<body>
<header>

</header>

<main>
    <div class="content">
        <h1 class="titleText">Class Grade Calculator</h1>
        <div class="topright">
            <%= link_to 'Log Out', sessions_destroy_path, :class=> "otherButton" %>
            <p>Hello, <%= current_user.studentName%>!!<br>
            <%= current_user.schoolName %></p>
        </div>
        <p id="intro">
            Enter your current grades for the different types of assignments, along with the weights that each of the
            assignments have. Your calculated final grade will be on the right.
        </p>
        <% if flash.any? %>
        <script>alert("Grades saved successfully to database!")</script>
        <% end %>
<div class="calcDiv">
<%= form_for([@user, User.find(session[:user_id]).grades.build], :class=>"studentInfo", :name=>"gradeInfo") do |form| %>
  
  <div id="leftSide">
    <div id="assignments">
      <p class="columnTitle">Assignment</p>
          <%= form.text_field :assignment1, :placeholder=>"Test 1"%>
          <%= form.text_field :assignment2%>
          <%= form.text_field :assignment3%>
          <%= form.text_field :assignment4%>
          <%= form.text_field :assignment5%>
          <%= form.text_field :assignment6%>
          <%= form.text_field :assignment7%>
          <%= form.text_field :assignment8%>
          <%= form.text_field :assignment9%>
          <%= form.text_field :assignment10%>
    </div>
    <div id="grades">
      <p class="columnTitle">Grade (%)</p>
          <%= form.text_field :gradeNum1, :type=>"number", :min=>"0", :max=>"120", :step=>"any", :placeholder=>"100", :id=>"gradeNum1"%>
          <%= form.text_field :gradeNum2, :type=>"number", :min=>"0", :max=>"120", :step=>"any", :id=>"gradeNum2"%>
          <%= form.text_field :gradeNum3, :type=>"number", :min=>"0", :max=>"120", :step=>"any", :id=>"gradeNum3"%>
          <%= form.text_field :gradeNum4, :type=>"number", :min=>"0", :max=>"120", :step=>"any", :id=>"gradeNum4"%>
          <%= form.text_field :gradeNum5, :type=>"number", :min=>"0", :max=>"120", :step=>"any", :id=>"gradeNum5"%>
          <%= form.text_field :gradeNum6, :type=>"number", :min=>"0", :max=>"120", :step=>"any", :id=>"gradeNum6"%>
          <%= form.text_field :gradeNum7, :type=>"number", :min=>"0", :max=>"120", :step=>"any", :id=>"gradeNum7"%>
          <%= form.text_field :gradeNum8, :type=>"number", :min=>"0", :max=>"120", :step=>"any", :id=>"gradeNum8"%>
          <%= form.text_field :gradeNum9, :type=>"number", :min=>"0", :max=>"120", :step=>"any", :id=>"gradeNum9"%>
          <%= form.text_field :gradeNum10, :type=>"number", :min=>"0", :max=>"120", :step=>"any", :id=>"gradeNum10"%>
    </div>
    <div id="weights">
      <p class="columnTitle">Weight (%)</p>
        <%= form.text_field :wieght1, :type=>"number", :min=>"0", :max=>"100", :step=>"any", :placeholder=>"40", :id=>"weight1"%>
        <%= form.text_field :weight2, :type=>"number", :min=>"0", :max=>"100", :step=>"any", :id=>"weight2"%>
        <%= form.text_field :weight3, :type=>"number", :min=>"0", :max=>"100", :step=>"any", :id=>"weight3"%>
        <%= form.text_field :weight4, :type=>"number", :min=>"0", :max=>"100", :step=>"any", :id=>"weight4"%>
        <%= form.text_field :weight5, :type=>"number", :min=>"0", :max=>"100", :step=>"any", :id=>"weight5"%>
        <%= form.text_field :weight6, :type=>"number", :min=>"0", :max=>"100", :step=>"any", :id=>"weight6"%>
        <%= form.text_field :weight7, :type=>"number", :min=>"0", :max=>"100", :step=>"any", :id=>"weight7"%>
        <%= form.text_field :weight8, :type=>"number", :min=>"0", :max=>"100", :step=>"any", :id=>"weight8"%>
        <%= form.text_field :weight9, :type=>"number", :min=>"0", :max=>"100", :step=>"any", :id=>"weight9"%>
        <%= form.text_field :weight10, :type=>"number", :min=>"0", :max=>"100", :step=>"any", :id=>"weight10"%>
    </div>
      <div id="buttonDiv">
        <input type="button" value="Calculate" class="submitButton" onClick="javascript: validate();">
        &nbsp;&nbsp;
        <input type="reset" value="Clear" class="submitButton" onClick="window.location.reload();">
        &nbsp;&nbsp;
        <%= form.submit("Save", :class=>"submitButton") %>
        &nbsp;&nbsp;
        <%= link_to 'Show Previous Log', calculator_gradeTable_path, :class=>"showLogButton" %>
      </div>
    </div>
     <div id="resultsDiv rightSide">
        <p id="resultsTitle">Results</p>
        <p>Your calculated final grade is  <strong><%= form.label :result, :id=>"gradeResult" %></strong></p>
        <%= hidden_field(:grade, :result, :id=>"hidden_result") %>
       <p>The total combined weight of the assignments you entered is <strong><%= form.label :weightAvg,:id=>"combinedWeight", :value=>"0" %></strong> percent.</p>
       <%= hidden_field(:grade, :weightAvg, :id=>"hidden_weightAvg") %>
    </div>
<% end %>
</div>
</main>

</body>
</html>

Grade_Calculator/app/views/calculator/gradeTable.html.erb
<!DOCTYPE html>
<!-- HTML file for Homepage of ITIS 3135 Project -->

<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Class Grade Calculator</title>
    <link rel="stylesheet" type="text/css" href="../stylesheets/main.css">
    <link rel="icon" type="image/x-icon" href="https://my.uncc.edu/sites/all/themes/custom/my_unc_charlotte/favicon.ico"/>
    <script src="../scripts/main.js"></script>
</head>
<body>
<header>

</header>

<main>
    <div class="content">
        <h1 class="titleText">Previous Log</h1>
        <div class="topright">
            <%= link_to 'Log Out', sessions_destroy_path, :class=> "otherButton" %>
            <p>Hello, <%= current_user.studentName%>!!<br>
            <%= current_user.schoolName %></p>
        </div>
        <% User.find(session[:user_id]).grades.each do |grade| %>
        <div id="leftSideTable">
            <div id="assignments">
              <p class="columnTitle">Assignment</p>
                  <p><%= grade.assignment1 %></p>
                  <p><%= grade.assignment2 %></p>
                  <p><%= grade.assignment3 %></p>
                  <p><%= grade.assignment4 %></p>
                  <p><%= grade.assignment5 %></p>
                  <p><%= grade.assignment6 %></p>
                  <p><%= grade.assignment7 %></p>
                  <p><%= grade.assignment8 %></p>
                  <p><%= grade.assignment9 %></p>
                  <p><%= grade.assignment10 %></p>
            </div>
            <div id="grades">
              <p class="columnTitle">Grade (%)</p>
                 <p><%= grade.gradeNum1 %></p>
                  <p><%= grade.gradeNum2 %></p>
                  <p><%= grade.gradeNum3 %></p>
                  <p><%= grade.gradeNum4 %></p>
                  <p><%= grade.gradeNum5 %></p>
                  <p><%= grade.gradeNum6 %></p>
                  <p><%= grade.gradeNum7 %></p>
                  <p><%= grade.gradeNum8 %></p>
                  <p><%= grade.gradeNum9 %></p>
                  <p><%= grade.gradeNum10 %></p>
            </div>
            <div id="weights">
              <p class="columnTitle">Weight (%)</p>
                <p><%= grade.wieght1 %></p>
                <p><%= grade.weight2 %></p>
                <p><%= grade.weight3 %></p>
                <p><%= grade.weight4 %></p>
                <p><%= grade.weight5 %></p>
                <p><%= grade.weight6 %></p>
                <p><%= grade.weight7 %></p>
                <p><%= grade.weight8 %></p>
                <p><%= grade.weight9 %></p>
                <p><%= grade.weight10 %></p>
            </div>
            <div id="weights">
                <p class="columnTitle">Result</p>
                <%= grade.result %>%
            </div>
            <div id="weights">
                <p class="columnTitle">Total Weight</p>
                <%= grade.weightAvg %>%
            </div>
        </div>
    <% end %>
    <%= link_to 'Back', calculator_gradeCalculator_path, :class=>"backButton" %>
    </div>
</main>
</body>
</html>

Grade_Calculator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GradeCalculator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Grade_Calculator/app/views/login/loginPage.html.erb
<!DOCTYPE html>
<!-- HTML file for Homepage of ITIS 3135 Project -->

<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Class Grade Calculator</title>
    <link rel="stylesheet" type="text/css" href="../stylesheets/main.css">
    <link rel="icon" type="image/x-icon" href="https://my.uncc.edu/sites/all/themes/custom/my_unc_charlotte/favicon.ico"/>
</head>

<body>
<header>

</header>

<main>
    <div class="content">
        <h1 class="titleText">Class Grade Calculator</h1>
        <p id="intro">
            Please sign-up to use the calculator. If you already have an account, click the login page button.
        </p>
        <div class="formDiv">
            <form class="studentInfo" name="studentInfo" action="#">
                <p class="fieldTitle">Email:</p>
                <input class="inputField" type="email" name="emailInput" required>
                <p class="fieldTitle">Password:</p>
                <input class="inputField" type="password" name="passwordInput" minlength="8" required>
                <br><br>
                <input class="submitButton" type="submit" value="Login">
            </form>
        </div>
        <div>
            <img id="studyingPicture" src="https://img.freepik.com/free-photo/education-concept-student-studying-brainstorming-campus-concept-close-up-students-discussing-their-subject-books-textbooks-selective-focus_1418-627.jpg?size=626&ext=jpg" alt="Studying Picture" width="400px">
        </div>
    </div>
</main>

<footer>
</footer>

</body>
</html>

Grade_Calculator/app/views/users/_form.html.erb
<!DOCTYPE html>
<!-- HTML file for Homepage of ITIS 3135 Project -->
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Class Grade Calculator</title>
    <link rel="stylesheet" type="text/css" href="stylesheets/main.css">
    <link rel="icon" type="image/x-icon" href="https://my.uncc.edu/sites/all/themes/custom/my_unc_charlotte/favicon.ico"/>
</head>

<body>
<header>

</header>
<main>
    <div class="content">
        <h1 class="titleText">Class Grade Calculator</h1>
        <p id="intro">
            Please sign-up to use the calculator. If you already have an account, click the login page button.
        </p>
        <div class="formDiv">
            <%= form_with(model: @user, local: true, :id=> "studentInfo", :action=> "javascript: passwordCheck()") do |form| %>
                
                <% if user.errors.any? %>
                <div id="error_explanation_signup">
                  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
                  
                  <ul>
                  <% user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
                
                <p class="fieldTitle">
                <%= form.label("Student Name:") %> </p>
                <%= form.text_field :studentName, :class=>"inputField" %>
              
            
              <p class="fieldTitle">
                <%= form.label("Email:") %> </p>
                <%= form.text_field :email, :class=>"inputField", :type=>"email" %>
              
            
            
               <p class="fieldTitle">
                <%= form.label("Password:") %> </p>
                <%= form.password_field :password, :class=>"inputField" %>
              
            
            
              <p class="fieldTitle">
                <%= form.label("Confirm Password:") %> </p>
                <%= form.password_field :password_confirmation, :class=>"inputField" %>
             
            
              <p class="fieldTitle">
                <%= form.label("School Name:") %> </p>
                <%= form.text_field :schoolName, :class=>"schoolNameField"%>
              <br><br>
              <%= form.submit :class=>"submitButton", :value=>"Sign-Up",  data: { disable_with: false }  %>
              &nbsp; &nbsp;
              <%= link_to 'Login', new_session_path, :class=> "otherButton" %>
          
            <% end %>

        </div>
        <div>
            <%= image_tag("studying.jpg", :id=>"studyingPicture_signup", :alt=>"Studying Picture") %>
        </div>
    </div>
</main>

<footer>
    
</footer>

</body>
</html>

Grade_Calculator/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Grade_Calculator/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Studentname</th>
      <th>Schoolname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.studentName %></td>
        <td><%= user.schoolName %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Grade_Calculator/app/views/users/new.html.erb
<%= render 'form', user: @user %>

Grade_Calculator/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Studentname:</strong>
  <%= @user.studentName %>
</p>

<p>
  <strong>Schoolname:</strong>
  <%= @user.schoolName %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>